name: remoteforpc
repository: https://github.com/yourusername/remoteforpc

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.10.0"
    
    dependencies:
      melos: ^6.0.0

  version:
    branch: main
    message: "chore(release): publish packages"

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run Dart analyzer in all packages

  format:
    run: melos exec -- dart format .
    description: Format all Dart files

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages
    packageFilters:
      dirExists: test

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  get:
    run: melos exec -- flutter pub get
    description: Get dependencies for all packages

  build:server:
    run: flutter build macos
    exec:
      concurrency: 1
    packageFilters:
      scope: server_desktop
    description: Build macOS server app

  build:client:
    run: flutter build ios
    exec:
      concurrency: 1
    packageFilters:
      scope: client_mobile
    description: Build iOS client app

  run:server:
    run: flutter run -d macos
    exec:
      concurrency: 1
    packageFilters:
      scope: server_desktop
    description: Run server app on macOS

  run:client:
    run: flutter run
    exec:
      concurrency: 1
    packageFilters:
      scope: client_mobile
    description: Run client app
